apiVersion: v1
kind: Secret
metadata:
  name: pvt-docker-creds
data:
  .dockerconfigjson: base64-encoded-docker-config-json
type: kubernetes.io/dockerconfigjson

#echo -n '{"auths":{"https://index.docker.io/v1/":{"username":"your-dockerhub-username","password":"your-dockerhub-password","email":"your-email@example.com"}}}' | base64 -w 0
