apiVersion: v1
kind: Secret
metadata:
  name: pvt-docker-creds
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzdGFya3l2IiwicGFzc3dvcmQiOiJjWWh0aW0tOHZvY3pvLWJhZ3JlaCIsImVtYWlsIjoieWFzaHZhbnRoNG1heUBnbWFpbC5jb20ifX19
type: kubernetes.io/dockerconfigjson

#echo -n '{"auths":{"https://index.docker.io/v1/":{"username":"your-dockerhub-username","password":"your-dockerhub-password","email":"your-email@example.com"}}}' | base64 -w 0
