apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-webapp
spec:
  podSelector:
    matchLabels:
      app: webapp
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend