apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snorlax
  namespace: snorlax
spec:
  interval: 5m
  chart:
    spec:
      chart: snorlax
      version: "0.7.0"
      sourceRef:
        kind: HelmRepository
        name: snorlax
        namespace: flux-system
  values:
    watcher:
      namespaces:
        - default
    snorlax:
      timezone: "UTC"
  install:
    createNamespace: true
