---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-bot
  namespace: default
imagePullSecrets:
  - name: aws-ecr-token-facets-config-auto
  - name: aws-ecr-token-facetsaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-bot-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status", "pods/exec", "events"]
  verbs: ["get", "list", "watch", "describe", "create"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale", "replicasets"]
  verbs: ["get", "list", "patch", "update", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-bot-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops-bot-role
subjects:
- kind: ServiceAccount
  name: devops-bot
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-bot-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-bot
  template:
    metadata:
      labels:
        app: devops-bot
    spec:
      serviceAccountName: devops-bot
      enableServiceLinks: false
      containers:
        - name: devops-bot
          image: ecr.aws.region.amazonaws.com/repo:latest
          imagePullPolicy: Always
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: devops-bot-secrets
                  key: slack-token
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: devops-bot-secrets
                  key: slack-signing-secret
            - name: VERIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: devops-bot-secrets
                  key: slack-verification-token
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: devops-bot-secrets
                  key: auth-token
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: devops-bot-secrets
                  key: slack-webhook
            - name: APP_ENV
              value: "production"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: aws-ecr-token
        - name: aws-ecr-token-account

---
apiVersion: v1
kind: Service
metadata:
  name: devops-bot
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 8080
  selector:
    app: devops-bot
  type: ClusterIP