name: Build, Push Docker Image to Docker Hub and AWS ECR
on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main
jobs:
  docker_build:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get short SHA and branch name
        id: slug
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9-]//g')
          IMAGE_TAG="$BRANCH_NAME-$SHORT_SHA-devops-learning"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Checking Critical Values
        run: "echo New Image Tag: ${{ env.IMAGE_TAG }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: "true"
          tags: docker.io/starkyv/devops-learning:${{ env.IMAGE_TAG }}
          labels: latest
